server:
  port: 9090

logging:
  level:
    org.springframework.data.mongodb: DEBUG


spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

    show-sql: true

