server:
  port: 9090

logging:
  level:
    org.springframework.data.mongodb: DEBUG


spring:
  datasource:
    url: jdbc:postgresql://HOST:5432/dbname
    username: your_user
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true

